// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: order_status_notes.proto

package order_notes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentEnum int32

const (
	PaymentEnum_waiting_for_payment PaymentEnum = 0
	PaymentEnum_collecting          PaymentEnum = 1
	PaymentEnum_shipping            PaymentEnum = 2
	PaymentEnum_waiting_on_branch   PaymentEnum = 3
	PaymentEnum_finished            PaymentEnum = 4
	PaymentEnum_cancelled           PaymentEnum = 5
)

// Enum value maps for PaymentEnum.
var (
	PaymentEnum_name = map[int32]string{
		0: "waiting_for_payment",
		1: "collecting",
		2: "shipping",
		3: "waiting_on_branch",
		4: "finished",
		5: "cancelled",
	}
	PaymentEnum_value = map[string]int32{
		"waiting_for_payment": 0,
		"collecting":          1,
		"shipping":            2,
		"waiting_on_branch":   3,
		"finished":            4,
		"cancelled":           5,
	}
)

func (x PaymentEnum) Enum() *PaymentEnum {
	p := new(PaymentEnum)
	*p = x
	return p
}

func (x PaymentEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_order_status_notes_proto_enumTypes[0].Descriptor()
}

func (PaymentEnum) Type() protoreflect.EnumType {
	return &file_order_status_notes_proto_enumTypes[0]
}

func (x PaymentEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentEnum.Descriptor instead.
func (PaymentEnum) EnumDescriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_status_notes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_notes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{0}
}

type OrderNotesPrimaryKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *OrderNotesPrimaryKey) Reset() {
	*x = OrderNotesPrimaryKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_status_notes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderNotesPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderNotesPrimaryKey) ProtoMessage() {}

func (x *OrderNotesPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_notes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderNotesPrimaryKey.ProtoReflect.Descriptor instead.
func (*OrderNotesPrimaryKey) Descriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{1}
}

func (x *OrderNotesPrimaryKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateOrderNotes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string      `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status  PaymentEnum `protobuf:"varint,2,opt,name=status,proto3,enum=order_notes.PaymentEnum" json:"status,omitempty"`
	UserId  string      `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason  string      `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CreateOrderNotes) Reset() {
	*x = CreateOrderNotes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_status_notes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderNotes) ProtoMessage() {}

func (x *CreateOrderNotes) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_notes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderNotes.ProtoReflect.Descriptor instead.
func (*CreateOrderNotes) Descriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderNotes) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderNotes) GetStatus() PaymentEnum {
	if x != nil {
		return x.Status
	}
	return PaymentEnum_waiting_for_payment
}

func (x *CreateOrderNotes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderNotes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type OrderNotes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId   string      `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status    PaymentEnum `protobuf:"varint,3,opt,name=status,proto3,enum=order_notes.PaymentEnum" json:"status,omitempty"`
	UserId    string      `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason    string      `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt string      `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *OrderNotes) Reset() {
	*x = OrderNotes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_status_notes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderNotes) ProtoMessage() {}

func (x *OrderNotes) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_notes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderNotes.ProtoReflect.Descriptor instead.
func (*OrderNotes) Descriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{3}
}

func (x *OrderNotes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderNotes) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderNotes) GetStatus() PaymentEnum {
	if x != nil {
		return x.Status
	}
	return PaymentEnum_waiting_for_payment
}

func (x *OrderNotes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderNotes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderNotes) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UpdateOrderNotes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId string      `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status  PaymentEnum `protobuf:"varint,3,opt,name=status,proto3,enum=order_notes.PaymentEnum" json:"status,omitempty"`
	UserId  string      `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason  string      `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *UpdateOrderNotes) Reset() {
	*x = UpdateOrderNotes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_status_notes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderNotes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderNotes) ProtoMessage() {}

func (x *UpdateOrderNotes) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_notes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderNotes.ProtoReflect.Descriptor instead.
func (*UpdateOrderNotes) Descriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrderNotes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrderNotes) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateOrderNotes) GetStatus() PaymentEnum {
	if x != nil {
		return x.Status
	}
	return PaymentEnum_waiting_for_payment
}

func (x *UpdateOrderNotes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateOrderNotes) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetListOrderNotesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetListOrderNotesRequest) Reset() {
	*x = GetListOrderNotesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_status_notes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListOrderNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOrderNotesRequest) ProtoMessage() {}

func (x *GetListOrderNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_notes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOrderNotesRequest.ProtoReflect.Descriptor instead.
func (*GetListOrderNotesRequest) Descriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{5}
}

func (x *GetListOrderNotesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetListOrderNotesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetListOrderNotesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count      int64         `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	OrderNotes []*OrderNotes `protobuf:"bytes,2,rep,name=OrderNotes,proto3" json:"OrderNotes,omitempty"`
}

func (x *GetListOrderNotesResponse) Reset() {
	*x = GetListOrderNotesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_status_notes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListOrderNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOrderNotesResponse) ProtoMessage() {}

func (x *GetListOrderNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_status_notes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOrderNotesResponse.ProtoReflect.Descriptor instead.
func (*GetListOrderNotesResponse) Descriptor() ([]byte, []int) {
	return file_order_status_notes_proto_rawDescGZIP(), []int{6}
}

func (x *GetListOrderNotesResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetListOrderNotesResponse) GetOrderNotes() []*OrderNotes {
	if x != nil {
		return x.OrderNotes
	}
	return nil
}

var File_order_status_notes_proto protoreflect.FileDescriptor

var file_order_status_notes_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6e,
	0x6f, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x26, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e,
	0x75, 0x6d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0xb9, 0x01, 0x0a, 0x0a,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f,
	0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x48, 0x0a, 0x18, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x6a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x4e, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e,
	0x6f, 0x74, 0x65, 0x73, 0x52, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73,
	0x2a, 0x78, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12,
	0x17, 0x0a, 0x13, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6f, 0x72, 0x5f, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x77, 0x61, 0x69, 0x74, 0x69, 0x6e,
	0x67, 0x5f, 0x6f, 0x6e, 0x5f, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x10, 0x03, 0x12, 0x0c, 0x0a,
	0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x63,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x05, 0x32, 0x81, 0x03, 0x0a, 0x10, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x12,
	0x42, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x1a, 0x17, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x12, 0x21,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65,
	0x79, 0x1a, 0x17, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x06,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x25, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e,
	0x6f, 0x74, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73,
	0x1a, 0x17, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x06, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f,
	0x74, 0x65, 0x73, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x65, 0x73, 0x50, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x4b, 0x65, 0x79, 0x1a, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x16,
	0x5a, 0x14, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_status_notes_proto_rawDescOnce sync.Once
	file_order_status_notes_proto_rawDescData = file_order_status_notes_proto_rawDesc
)

func file_order_status_notes_proto_rawDescGZIP() []byte {
	file_order_status_notes_proto_rawDescOnce.Do(func() {
		file_order_status_notes_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_status_notes_proto_rawDescData)
	})
	return file_order_status_notes_proto_rawDescData
}

var file_order_status_notes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_status_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_status_notes_proto_goTypes = []interface{}{
	(PaymentEnum)(0),                  // 0: order_notes.PaymentEnum
	(*Empty)(nil),                     // 1: order_notes.Empty
	(*OrderNotesPrimaryKey)(nil),      // 2: order_notes.OrderNotesPrimaryKey
	(*CreateOrderNotes)(nil),          // 3: order_notes.CreateOrderNotes
	(*OrderNotes)(nil),                // 4: order_notes.OrderNotes
	(*UpdateOrderNotes)(nil),          // 5: order_notes.UpdateOrderNotes
	(*GetListOrderNotesRequest)(nil),  // 6: order_notes.GetListOrderNotesRequest
	(*GetListOrderNotesResponse)(nil), // 7: order_notes.GetListOrderNotesResponse
}
var file_order_status_notes_proto_depIdxs = []int32{
	0, // 0: order_notes.CreateOrderNotes.status:type_name -> order_notes.PaymentEnum
	0, // 1: order_notes.OrderNotes.status:type_name -> order_notes.PaymentEnum
	0, // 2: order_notes.UpdateOrderNotes.status:type_name -> order_notes.PaymentEnum
	4, // 3: order_notes.GetListOrderNotesResponse.OrderNotes:type_name -> order_notes.OrderNotes
	3, // 4: order_notes.OrderStatusNotes.Create:input_type -> order_notes.CreateOrderNotes
	2, // 5: order_notes.OrderStatusNotes.GetById:input_type -> order_notes.OrderNotesPrimaryKey
	6, // 6: order_notes.OrderStatusNotes.GetAll:input_type -> order_notes.GetListOrderNotesRequest
	5, // 7: order_notes.OrderStatusNotes.Update:input_type -> order_notes.UpdateOrderNotes
	2, // 8: order_notes.OrderStatusNotes.Delete:input_type -> order_notes.OrderNotesPrimaryKey
	4, // 9: order_notes.OrderStatusNotes.Create:output_type -> order_notes.OrderNotes
	4, // 10: order_notes.OrderStatusNotes.GetById:output_type -> order_notes.OrderNotes
	7, // 11: order_notes.OrderStatusNotes.GetAll:output_type -> order_notes.GetListOrderNotesResponse
	4, // 12: order_notes.OrderStatusNotes.Update:output_type -> order_notes.OrderNotes
	1, // 13: order_notes.OrderStatusNotes.Delete:output_type -> order_notes.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_status_notes_proto_init() }
func file_order_status_notes_proto_init() {
	if File_order_status_notes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_status_notes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_status_notes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderNotesPrimaryKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_status_notes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderNotes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_status_notes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderNotes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_status_notes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderNotes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_status_notes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListOrderNotesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_status_notes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListOrderNotesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_status_notes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_status_notes_proto_goTypes,
		DependencyIndexes: file_order_status_notes_proto_depIdxs,
		EnumInfos:         file_order_status_notes_proto_enumTypes,
		MessageInfos:      file_order_status_notes_proto_msgTypes,
	}.Build()
	File_order_status_notes_proto = out.File
	file_order_status_notes_proto_rawDesc = nil
	file_order_status_notes_proto_goTypes = nil
	file_order_status_notes_proto_depIdxs = nil
}
